services:
  medicord:
    container_name: medicord
    build:
      context: .
      dockerfile: ./Dockerfile.php
      args:
        - PHP_VERSION=php:8.2-apache
    volumes:
      - ./medicord/:/var/www/html/:rw
    ports:
      - 8081:80
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 9090:80
    environment:
      - PMA_HOST=host.docker.internal
      - PMA_ARBITRARY=1
      - PMA_ABSOLUTE_URI=http://pma.localhost
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  nginx:
    container_name: nginx
    # image: nginx:latest
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    ports:
      - 80:80
    volumes:
      # - ./conf/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./conf/var/log/nginx/:/var/log/nginx/
      #- ./conf/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - medicord
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
