FROM nginx:latest

COPY ./conf/etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY ./conf/var/www/html/* /var/www/html/

# COPY ./conf/etc/nginx/certs/* /etc/nginx/certs/

WORKDIR /var/www/html
